### ISSUE TITLE
Doesn't work on node version > 5 due to outdated dependency on command-line-args

### ISSUE THREAD

**Issue by dlockhart** [PolymerLabs/web-component-shards#20]
If you try to run `web-component-shards` on a version of node greater than 5, you get the following error:

```
/node_modules/column-layout/lib/rows.js:69
  return columns.map(column => {
                ^

TypeError: Cannot read property 'map' of undefined
    at objectToIterable (/node_modules/column-layout/lib/rows.js:69:17)
    at arrayify.forEach.row (/node_modules/column-layout/lib/rows.js:20:53)
    at Array.forEach (native)
    at Rows.load (/node_modules/column-layout/lib/rows.js:20:20)
    at new Rows (/node_modules/column-layout/lib/rows.js:15:10)
    at Rows.map (native)
    at Table.getWrapped (/node_modules/column-layout/lib/table.js:74:22)
    at Table.getLines (/node_modules/column-layout/lib/table.js:92:29)
    at Table.renderLines (/node_modules/column-layout/lib/table.js:108:22)
    at Table.render (/node_modules/column-layout/lib/table.js:118:17)
```

If you trace the dependency tree back, it's coming from `command-line-args`, which depends on `column-layout`, which has since been renamed to `table-layout`. There's a newer version of `command-line-args` that seems to fix the problem, but there are some breaking changes involved in upgrading to it.

**Comment by CodeBaboon** [comment]
Would be awesome to see this fixed, just bit me as well.
